global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'serp_keyword_api'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000'] 