apiVersion: apps/v1
kind: Deployment
metadata:
  name: serp-keyword-api
  labels:
    app: serp-keyword-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serp-keyword-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: serp-keyword-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: api
        image: ${DOCKER_REGISTRY}/serp-keyword-api:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: serp-keyword-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: serp-keyword-secrets
              key: redis-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: serp-keyword-secrets
              key: openai-api-key
        - name: SERP_API_KEY
          valueFrom:
            secretKeyRef:
              name: serp-keyword-secrets
              key: serp-api-key
        - name: ENABLE_TRACING
          value: "true"
        - name: TRACING_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: serp-keyword-config
              key: log-level
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      imagePullSecrets:
      - name: registry-secret 